const NONE_USER = 'NONE_USER',
    INCORRECT_DATA = 'INCORRECT_DATA',
    LOGIN_USED = 'LOGIN_USED',
    SERVER_ERROR = 'SERVER_ERROR',
    CONNECT_ERROR = 'CONNECT_ERROR',
    WAITING = 'WAITING',
    READY = 'READY';

module.exports = {NONE_USER, INCORRECT_DATA, LOGIN_USED, SERVER_ERROR, CONNECT_ERROR, WAITING, READY};